services:
  #  TODO add 'web' service for serving contact page

  # See: https://docs.n8n.io/hosting/installation/server-setups/docker-compose/#6-create-docker-compose-file
  n8n:
    build: .
    image: cpadm:n8n
    restart: unless-stopped
    ports:
      - "5678:5678"

    # Required by at least ZMAP
    cap_add:
      - NET_RAW
      - NET_ADMIN

    env_file: "n8n.env"

    volumes:
      - n8n_data:/home/root/.n8n


volumes:
  n8n_data:
