#!/usr/sbin/nft -f

flush ruleset

table inet filter {

        # 145.126.0.0/17        # UT wlan range
        # 130.89.0.0/16         # UT fixed range
        # 130.89.144.32/27      # DACS production vm range
        # 130.89.144.64/26      # DACS bare-metal servers (old 'simpleweb' range)
        # 192.87.172.0/24       # DACS playground vm range

        chain input {
                type filter hook input priority 0; policy drop;

                # accept any localhost traffic
                iif lo accept

                # accept traffic originated from us and accepted connections
                ct state established,related accept

                # accept ssh from ut ranges
                ip saddr 130.89.0.0/16 tcp dport 22 ct state new accept
		        ip saddr 145.126.0.0/17 tcp dport 22 ct state new accept
                ip6 saddr 2001:67c:2564::/48 tcp dport 22 ct state new accept

                # accept HTTP(S) from all
                # Also needed for let's TLS challenge
                tcp dport { 80, 443 } ct state new accept

		        # Accept traffic to n8n (container-level filtering happens in DOCKER-USER)
		        tcp dport 5678 ct state new accept

                # accept icmp echo
                icmp type echo-request accept

                # accept neighbour discovery otherwise IPv6 connectivity breaks.
                ip6 nexthdr icmpv6 icmpv6 type { echo-request, nd-neighbor-solicit,  nd-router-advert, nd-neighbor-advert } accept

        }
        chain forward {
                type filter hook forward priority 0; policy drop;

                 # allow replies
                 ct state established,related accept
        }
        chain output {
                type filter hook output priority 0; policy accept;
        }

}

table ip filter {

    chain DOCKER-USER {

        # Allow n8n only from UT networks
        ip saddr { 130.89.0.0/16, 145.126.0.0/17 } tcp dport 5678 accept

        # Drop everything else trying to reach containers
        tcp dport 5678 drop

        # Hand remaining traffic back to Docker
        return
    }
}