name: Test Docker container

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run-n8n-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build custom Docker image
        run: docker build -t cpadm:n8n .

      - name: Run container in background
        run: |
          docker compose -p n8n-scanning up -d
          # TODO use the readiness or /healthz endpoint
          sleep 20

      - name: Check if all tools are available inside the container
        run: |
          docker exec n8n-scanning-n8n-1 sh -c "nmap --version"
          # MASSCAN always exits with code 1 here, suppress it
          docker exec n8n-scanning-n8n-1 sh -c "masscan --version" || true
          docker exec n8n-scanning-n8n-1 sh -c "zmap --version"

# TODO Also test with n8n workflow (in combination with our custom nodes)
#      - name: (Optional) Run an n8n workflow
#        run: |
#          echo "Triggering internal n8n workflow via API (if configured)..."
#          curl -s -X POST http://localhost:5678/webhook-test

# TODO Publish container
