name: Test Docker container

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run-n8n-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create default 'n8n.env' file
        run: |
          cp n8n.env.default n8n.env

      - name: Build image and run container in background
        run: |
          docker compose -p n8n-scanning up -d --wait

      - name: Check if all tools are available inside the container
        run: |
          docker exec n8n-scanning-n8n-1 sh -c "nmap --version"
          # MASSCAN always exits with code 1 here, suppress it
          docker exec n8n-scanning-n8n-1 sh -c "masscan --version" || true
          docker exec n8n-scanning-n8n-1 sh -c "zmap --version"


# TODO Run /tests here, but somehow we need to generate an API key?

# TODO Publish container
