name: Test Docker container

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run-n8n-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create default 'n8n.env' file
        run: |
          cp n8n.env.default n8n.env

      - name: Build image and run container in background
        run: |
          docker compose -p n8n-scanning up -d --wait

      - name: Check if all tool dependencies are met
        run: |
          docker exec n8n-scanning-n8n-1 sh -c "ldd /usr/bin/nmap"
          docker exec n8n-scanning-n8n-1 sh -c "ldd /usr/bin/masscan"
          docker exec n8n-scanning-n8n-1 sh -c "ldd /usr/sbin/zmap"

      - name: Check if all tools are available inside the container
        run: |
          docker exec n8n-scanning-n8n-1 sh -c "nmap --version"
          # MASSCAN always exits with code 1 here, suppress it
          docker exec n8n-scanning-n8n-1 sh -c "masscan --version" || true
          docker exec n8n-scanning-n8n-1 sh -c "zmap --version"

      - name: Run n8n workflow with custom nodes
        timeout-minutes: 1
        run: |
          echo "Upload and trigger workflow with Nmap for scanme.nmap.org"
          curl -X POST http://localhost:5678/api/v1/workflows \
               -H "Content-Type: application/json" \
               -d @tests/workflows/Nmap.json
          curl -s -X POST http://localhost:5678/webhook/4fbcd73c-c822-4be7-b984-03ea4cf5ef44
#          TODO Make assertions on output

# TODO Publish container
